#!/bin/sh -x

export LC_ALL=en_US.UTF-8

# === 🌐 Detectar idioma del sistema ===
LANG_CODE=$(echo "$LANG" | cut -d '_' -f1 | tr '[:upper:]' '[:lower:]')

# === 🗣️ Textos según idioma ===
set_texts() {
    case "$1" in
        es)
            LABEL_SHUTDOWN="Apagar"
            LABEL_LOCK="Bloquear"
            LABEL_RESTART_WM="Reiniciar WM"
            LABEL_REBOOT="Reiniciar"
            LABEL_PROMPT="Consola"
            LABEL_SUSPEND="Suspender"
            LABEL_SHUTDOWN_EQUIP="Apagar"
            LABEL_RESTART_WM_DESC="Reiniciar WM"
            LABEL_REBOOT_DESC="Reiniciar"
            LABEL_SUSPEND_DESC="Suspender"
            ;;
        *)
            LABEL_SHUTDOWN="Shutdown"
            LABEL_LOCK="Lock"
            LABEL_RESTART_WM="Restart WM"
            LABEL_REBOOT="Reboot"
            LABEL_PROMPT="Prompt"
            LABEL_SUSPEND="Suspend"
            LABEL_SHUTDOWN_EQUIP="Shutdown Equipment"
            LABEL_RESTART_WM_DESC="Restart Window Manager"
            LABEL_REBOOT_DESC="Reboot system"
            LABEL_SUSPEND_DESC="Suspend or Hibernate"
            ;;
    esac
}

set_texts "$LANG_CODE"

# === 🎨 Iconos y estilo ===
icon_theme=$(grep gtk-icon-theme-name ~/.gtkrc-2.0 | cut -d= -f2 | tr -d ' ' | sed 's/"//g')
icon_name=system-shutdown
icon_path=$(find /usr/share/icons/$icon_theme -type f -name "$icon_name.*" | head -n 1)
font="TerminessNerdFont"

# === 🖼️ Botones con íconos y texto ===
T1="<span color='#AF636A' font='44'>  </span>
<span font='$font 20'>  $LABEL_SHUTDOWN</span>"
T2="<span color='#A3BE8C' font='44'>    </span>
<span font='$font 20'>  $LABEL_LOCK</span>"
T3="<span color='#BBA467' font='44'>   </span>
<span font='$font 20'>$LABEL_RESTART_WM</span>"
T4="<span color='#797179' font='44'>  </span>
<span font='$font 20'>$LABEL_REBOOT</span>"
T5="<span color='#8E8E8E' font='44'>  </span>
<span font='$font 20'>$LABEL_PROMPT</span>"
T6="<span color='#F6B40D' font='44'>   </span>
<span font='$font 20'> $LABEL_SUSPEND</span>"

# === 🖱️ Menú YAD ===
yad --title="Shutdown-gui" --window-icon "$icon_name" --center --form --no-buttons --undecorated --timeout=10 --timeout-indicator=right \
  --columns="3" \
  --field=" $T1!!<span font='$font 12'>$LABEL_SHUTDOWN_EQUIP</span>  :fbtn" "wmpoweroff" \
  --field=" $T2!!<span font='$font 12'>$LABEL_LOCK</span>   :fbtn" "xlock" \
  --field=" $T3!!<span font='$font 12'>$LABEL_RESTART_WM_DESC</span>   :fbtn" "restartwm" \
  --field=" $T4!!<span font='$font 12'>$LABEL_REBOOT_DESC</span>  :fbtn" "wmreboot" \
  --field=" $T5!!<span font='$font 12'>$LABEL_PROMPT</span>   :fbtn" "wmexit" \
  --field=" $T6!!<span font='$font 12'>$LABEL_SUSPEND_DESC</span>  :fbtn" "/etc/acpi/actions/suspend.sh"
